trigger:
- main
pool: shikha

steps:
- task: TerraformInstaller@1
  inputs:
    terraformVersion: '1.12.2'

- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/Environments/Dev'
    backendServiceArm: 'newpro_conn'
    backendAzureRmResourceGroupName: 'newprorg'
    backendAzureRmStorageAccountName: 'newprostg'
    backendAzureRmContainerName: 'newprobox'
    backendAzureRmKey: 'terraform.tfstate'

- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'plan'
    workingDirectory: '$(System.DefaultWorkingDirectory)/Environments/Dev'
    environmentServiceNameAzureRM: 'newpro_conn'

- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'apply'
    workingDirectory: '$(System.DefaultWorkingDirectory)/Environments/Dev'
    environmentServiceNameAzureRM: 'newpro_conn'

